version: "3.8"

services:
  frontend:
    container_name: book_project_frontend
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
      args:
        PROFILE: ${PROFILE:-dev}
    volumes:
      - ./frontend/src:/app/src
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: postgres:14
    container_name: book_project_db
    restart: always
    environment:
      POSTGRES_DB: book_project_db
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpassword
    ports:
      - "5433:5432"   # mapa container:host => host usa 5433
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dbuser -d book_project_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    container_name: book_project_backend
    build:
      context: ./backend
      dockerfile: ./Dockerfile
      args:
        mvn_arg: clean package -DskipTests
        DB_HOSTNAME: db
        DB_PORT: 5432
        DB_NAME: book_project_db
        DB_USERNAME: dbuser
        DB_PASSWORD: dbpassword
    restart: "no"
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_DATABASE=book_project_db
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpassword
      - POSTGRES_HOSTNAME=db
      - POSTGRES_PORT=5432
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data: